#!/usr/bin/python3

from functools import reduce
# The sequence of triangle numbers is generated by adding the natural numbers.
# So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five
# hundred divisors?

def triangle():
    '''Add natural numbers - 1,3,6,10,15 ...'''
    count = t = 1
    while True:
        yield t
        count += 1
        t += count

def get_factors(n):
    '''Returns a list of the factors of n'''
    from math import sqrt
    r = any(n%i == 0 for i in range(3, int(sqrt(n))+1,2))
    if n == 1 or n == 2 or (not n%2 == 0 and not r): 
        return[n]
    l = []
    i = 2
    limit = (n/2)+1
    while i <= limit:
        while n % i == 0:
            l.append(i)
            n = n/i
        i += 1
        if n == 1: 
            break
    return l

from operator import mul
num = 500
of = 2
for t in triangle():
    l = []
    f = get_factors(t)
    while len(f) != 0:
        a = f.count(f[0])
        l.append(a)
        del f[:a]
    of = reduce(mul, [l[x]+1 for x in range(len(l))])
    if of > num:
        break
    
print(t)
