#!/usr/bin/python3

'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fib():
	a = 1
	b = 2
	yield a
	yield b

	while True:
		old_b = b
		b = a+b
		a = old_b
		yield b

result = 0
for z in fib():
	if z >= 4000000:
		break
	
	if z % 2 == 0:
		result += z

print(result)

