/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

// Fibinacci struct
struct Fib {
    count: u64,
    a: u64,
    b: u64,
}

// Struct new() helper method
impl Fib {
    fn new() -> Fib {
        Fib { 
            count: 0,
            a: 1, 
            b: 2, 
        }
    }
}

// Iterator
impl Iterator for Fib {

    // Yield u64 responses 
    type Item = u64;

    // Yield 1.0, 2.0. then as normal
    fn next(&mut self) -> Option<Self::Item> {
        self.count += 1;
        match self.count {
            1 => {
                Some(self.a) // 1
            }
            2=> {
                Some(self.b) // 2
            }
            _ => {
                let old_b = self.b;
                self.b = self.a + self.b;
                self.a = old_b;
                Some(self.b)
            }
        }
    }
}

fn main() {
    let mut result: u64 = 0;

    let mut fib = Fib::new();
    loop {
        let x = fib.next();
        if let Some(x) = x {
            if x >= 4000000 {
                break
            }
            if x % 2 == 0 {
                result += x
            }
        } 
    }
    println!("{}", result);    
}
